name: Release

on:
  push:
    tags:
      - v*

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          export VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,' | sed -e 's/^v//')
          jq --arg v "$VERSION" '.version="$v"' package.json > tmp && mv tmp package.json  
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: yarn npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
