# Copyright 2020 Marius Wilms, Christoph Labacher. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

name: Release

on:
  push:
    tags:
      - v*

jobs:
  publish-npm:
    name: Publish to NPM Registry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          export VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,' | sed -e 's/^v//')
          jq --arg v "$VERSION" '.version="$v"' package.json > tmp && mv tmp package.json  
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: https://registry.npmjs.org/
      - run: yarn
      - run: make build
      - run: yarn npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
